name: social_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  fluttertoast: ^8.0.6
  conditional_builder: ^1.0.2
  shared_preferences: ^2.0.5
  image_picker: ^0.7.5
  timeago: ^3.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.4
  app_popup_menu: ^1.0.0
  bubble_tab_indicator: ^0.1.6
  #firebase dependencies
  flutter_bloc: ^7.0.0
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_storage: ^8.0.6
  cloud_firestore: ^2.1.0
  firebase_messaging: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
